### ISSUE TITLE
add link to the article

### ISSUE THREAD

**Issue by jerabaul29** [KTH-FlowAI/DeepReinforcementLearning_RayleighBenard2D_Control#4]
TODO: add the link to the article when it is released to the readme.

We should also push the latest preprint to RG + ArXiv, with the updated link to this repo.

@joelvarunvasanth could you generate a new pdf of the latest paper version, with the updated github link to the present repo, and share it here? Then I will update it on RG :) .

I think @franalcantara you were the one who put the ArXiv paper online at https://arxiv.org/abs/2304.02370 , could you update there too once we get the updated files from @joelvarunvasanth ? :)

**Comment by joelvarunvasanth** [comment]
Done, it is attached.

[arxiv_manuscript_accepted.pdf](https://github.com/KTH-FlowAI/DeepReinforcementLearning_RayleighBenard2D_Control/files/11728405/arxiv_manuscript_accepted.pdf)

Also, in our overleaf project, shall i now replace aa_main.tex with ab_main_R1.tex, since the revision is now the main manuscript?

Another thing - what about the data availability statement - 
"The data that support the findings of this study will be available and open-access upon publication of the manuscript."
Now that the manuscript has been accepted, do we change this? I dont think it should matter since this is just the arxiv.

**Comment by jerabaul29** [comment]
Perfect, thanks :) . I think the data availability can be updated to also point to the GH repo. Can you send a new pdf version like this, and I will read through it one last time tomorrow and out on RG then :)

Agree you can overwrite the main tex file with the revised version.

**Comment by joelvarunvasanth** [comment]
Here it is with the updated data availability statement

[arxiv_manuscript_accepted.pdf](https://github.com/KTH-FlowAI/DeepReinforcementLearning_RayleighBenard2D_Control/files/11728476/arxiv_manuscript_accepted.pdf)

**Comment by franalcantara** [comment]
Thank for updating the documents Joel. I have submitted already the replacement in arxiv. The replacement is scheduled to be announced at Wed, 14 Jun 2023 00:00:00 GMT.

**Comment by jerabaul29** [comment]
Perfect, many thanks :) . It is also updated at https://www.researchgate.net/publication/369801232_Effective_control_of_two-dimensional_Rayleigh-Benard_convection_invariant_multi-agent_reinforcement_learning_is_all_you_need , visible in updated version now :) .

Closing as both ArXiv and RG should be updated or "on their way", let us re open later on if necessary :) .
